config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("modules.accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

project_name = settings.PROJECT_NAME

admin.site.site_header = f"{project_name} Admin"
admin.site.site_title = f"{project_name} Admin Portal"
admin.site.index_title = f"Welcome to {project_name} Portal"

modules/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from modules.accounts import views
from modules.accounts.views import SignupView

app_name = "accounts"

urlpatterns = [
    # path(
    #     "login/",
    #     auth_views.LogoutView.as_view(
    #         template_name="accounts/login.html",
    #     ),
    #     name="login",
    # ),
    path("", views.loginView, name="login"),
    path("signup", views.SignupView.as_view(), name="signup"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="accounts/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            success_url="/accounts/password_reset/done/",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_subject.txt",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/reset/done/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("home/", views.HomeView, name="home"),
]

modules/accounts/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _
from django import forms
from modules.accounts.models import RoleChoices
from django.db import transaction
from django.contrib.auth.forms import AuthenticationForm


User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField, "role": forms.ChoiceField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    role = forms.ChoiceField(choices=RoleChoices.choices)

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email", "role")
        field_classes = {"email": EmailField, "role": forms.ChoiceField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(forms.ModelForm):
    """
    A form for user registration/signup.
    """

    name = forms.CharField(max_length=255, required=True)
    email = forms.EmailField(max_length=156, required=True)
    phone = forms.CharField(max_length=20, required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password_confirmation = forms.CharField(
        label="Password Confirmation",
        widget=forms.PasswordInput,
    )

    class Meta:
        """
        Meta class for UserSignupForm.

        Specifies the model and fields to be used in the form.
        """

        model = User
        fields = ("name", "phone", "email", "password", "password_confirmation")

    def clean(self):
        """
        Clean method for additional form-wide validation.

        Raises:
            forms.ValidationError: If the passwords do not match.
        Returns:
            dict: The cleaned form data.
        """
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if password and password_confirmation and password != password_confirmation:
            raise forms.ValidationError("The passwords do not match.")

        return cleaned_data

    @transaction.atomic
    def save(self, commit=True):
        """
        Save method to create and save a new user instance.

        Args:
            commit (bool): If True, save the user instance to the database.

        Returns:
            User: The created user instance.
        """
        user = super().save(commit=False)
        user.is_active = True
        user.role = RoleChoices.SUPERUSER
        user.phone_no = self.cleaned_data["phone"]
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class CustomAuthenticationForm(AuthenticationForm):
    """
    A custom authentication form that extends Django's AuthenticationForm.
    """

    email = EmailField(
        label=_("Email address"),
        widget=forms.EmailInput(attrs={"class": "form-control"}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        fields = ["email", "password"]

    field_order = ["email", "password"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "username" in self.fields:
            del self.fields["username"]

modules/accounts/api/views.py
import requests

from django.contrib.auth import get_user_model
from modules.accounts.permissions import IsSuperUser
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from rest_framework_simplejwt.tokens import RefreshToken

from rest_framework_simplejwt.exceptions import InvalidToken, TokenError
from django.core.exceptions import ValidationError
from modules.accounts.api.serializers import (
    LoginSerializer,
    RegisterSerializer,
    UserSerializer,
)
from django.core.validators import validate_email


User = get_user_model()


class LoginViewSet(ModelViewSet, TokenObtainPairView):
    """
    API endpoint for user login and obtaining access and refresh tokens.
    """

    serializer_class = LoginSerializer
    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, context={"request": request}
        )
        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])
        except ValidationError as e:
            return Response(
                {"error": e.args[0]},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(serializer.validated_data, status=status.HTTP_200_OK)


class LogoutViewSet(ModelViewSet):
    """
    Logout view to invalidate the user's refresh token.
    """

    permission_classes = [IsAuthenticated]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        refresh_token = request.data.get("refresh_token")

        if not refresh_token:
            return Response(
                {"error": "Refresh token is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            # Blacklist the refresh token, making it invalid
            token = RefreshToken(refresh_token)
            token.blacklist()
            return Response(
                {"success": "User was successfully logged out."},
                status=status.HTTP_200_OK,
            )
        except Exception as e:
            return Response(
                {"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )


class RefreshViewSet(ModelViewSet, TokenRefreshView):
    """
    Endpoint allows all users to refresh their token,
    by passing the refresh token in order to get a new access token
    """

    permission_classes = (AllowAny,)
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])

        return Response(serializer.validated_data, status=status.HTTP_200_OK)


class RegisterViewSet(ModelViewSet):
    """
    ViewSet for user registration.

    Allows users to register by providing necessary information
    such as phone number, email, name, and password.
    """

    serializer_class = RegisterSerializer
    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        context = {"request": request}
        serializer = self.get_serializer(data=request.data, context=context)
        serializer.is_valid(raise_exception=True)

        try:
            user = serializer.save()
            refresh = RefreshToken.for_user(user)

            response_data = {
                "user": serializer.data,
                "access_token": str(refresh.access_token),
                "refresh_token": str(refresh),
            }

            return Response(response_data, status=status.HTTP_201_CREATED)
        except ValidationError as e:
            return Response(
                {"error": str(e)},
                status=status.HTTP_400_BAD_REQUEST,
            )


# Google Login
# https://www.googleapis.com/auth/userinfo.email
# https://developers.google.com/oauthplayground/
class GoogleSocialLoginViewSet(ModelViewSet):
    """
    Google Social Login, Use the url below to test the endpoint;
    https://www.googleapis.com/auth/userinfo.email
    https://developers.google.com/oauthplayground/
    return access_token from the url above
    """

    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        token = request.data.get("token")

        if not token:
            return Response(
                {"error": "Token is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            response = requests.get(
                "https://www.googleapis.com/oauth2/v2/userinfo",
                params={"access_token": token},
            )
            response.raise_for_status()
            response_data = response.json()

            email = response_data.get("email")
            if not email:
                return Response(
                    {"error": "Email not provided by Google"},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            # Validate email address format
            try:
                validate_email(email)
            except ValidationError:
                return Response(
                    {"error": "Invalid email address"},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            user, created = User.objects.get_or_create(email=email)
            if created:
                user.full_name = response_data.get("name", "")
                user.is_active = True
                user.set_unusable_password()
                user.save()

            token = RefreshToken.for_user(user)
            return Response(
                {
                    "refresh": str(token),
                    "access": str(token.access_token),
                },
                status=status.HTTP_200_OK,
            )
        except requests.HTTPError as e:
            return Response(
                {"error": f"Google API request failed: {e.response.text}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


class UserViewSet(ModelViewSet):
    """
    API endpoint that allows users to be viewed, created, updated, or deleted.
    """

    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [IsAuthenticated, IsSuperUser]
    http_method_names = ["get", "post", "put", "patch", "delete"]

modules/accounts/views.py
from django.contrib.auth import authenticate, login
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib import messages
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required

from modules.accounts.models import RoleChoices, User
from modules.accounts.forms import CustomAuthenticationForm, UserSignupForm


class SignupView(CreateView):
    """
    View for user registration/signup.
    """

    model = User
    form_class = UserSignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:login")

    def get_context_data(self, **kwargs):
        """
        Get the context data for rendering the template.
        """
        kwargs["user_type"] = RoleChoices.SUPERUSER
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        """
        Process a valid form submission.
        """
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect(self.success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))


def loginView(request):
    """
    View for user login.
    """
    if request.method == "POST":
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Login success.")
                # Redirect to the success page.
                return HttpResponseRedirect(reverse("accounts:home"))
    else:
        form = CustomAuthenticationForm()

    return render(request, "accounts/login.html", {"form": form})


@login_required
def HomeView(request):
    """
    View for the home page.
    """
    userQuery = User.objects.all()
    context = {
        "users": userQuery,
    }
    return render(request, "pages/home.html", context)

modules/templates/accounts/base.html
<!DOCTYPE html>
{%load static%} {%load crispy_forms_tags%}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <title>{%block head_title%}{%endblock%} | InterIntel!</title>
  </head>
  <body>
    {%block navBar%}
    {%endblock%}
    <!-- messages -->
    {% if messages %}
    <div class="container">
      <div class="messages p-3">
        {% for message in messages %} {% if message.tags %}
        <div
          class="alert {% if message.tags == 'error' %}alert-danger{% endif %} {% if message.tags == 'success' %}alert-success{% endif %} {% if message.tags == 'warning' %}alert-warning{% endif %} {% if message.tags == 'info' %}alert-info{% endif %}"
          role="alert"
        >
          {{ message }}
        </div>
        {% else %}
        <div class="alert alert-secondary" role="alert">{{ message }}</div>
        {% endif %} {% endfor %}
      </div>
    </div>
    {% endif %} {%block content%} {%endblock%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

modules/templates/accounts/login.html
{% extends "accounts/base.html" %} {% load i18n %} {% load crispy_forms_tags %}

<!--Block Header-->
{% block head_title %} {% translate "Sign In" %} {% endblock head_title %}

<!--Block Content-->
{% block content %}
<div class="container">
  <div class="row h-100 justify-content-center align-items-center">
    <div class="col-md-4 mt-5">
      <div class="card shadow-md mt-5">
        <div class="card-header text-center" style="background-color: #02474c">
          <legend style="color: #ffffff">Welcome Back,</legend>
          <h6 style="color: #ffffff">sign in to continue</h6>
        </div>

        <div class="card-body">
          <form
            method="POST"
            action="{% url 'accounts:login' %}"
            enctype="multipart/form-data"
          >
            {%csrf_token%} {{form|crispy}}
            <!-- 2 column grid layout for inline styling -->
            <div class="row mb-4">
              <div class="col d-flex justify-content-center">
                <!-- Checkbox -->
                <div class="form-check">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    value=""
                    id="form2Example31"
                    checked
                  />
                  <label class="form-check-label" for="form2Example31">
                    Remember me
                  </label>
                </div>
              </div>

              <div class="col">
                <!-- Simple link -->
                <a href="{%url 'accounts:password_reset'%}">Forgot password?</a>
              </div>
            </div>

            <!-- Submit button -->
            <button
              type="submit"
              class="btn btn-outline-primary col-md-12 btn-block mb-4"
            >
              Sign in
            </button>

            <!-- Register buttons -->
            <div class="text-center">
              <p>
                Don't have an account?
                <a href="{%url 'accounts:signup'%}">Register Here</a>
              </p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

modules/templates/accounts/logout.html
{% extends "accounts/base.html" %} {% load i18n %}

<!--Block Header-->
{% block head_title %} {% translate "Logout" %} {% endblock head_title %}
{%block content%}
<h1>Logout Successful</h1>
{%endblock%}

modules/templates/accounts/password_reset.html
{% extends "accounts/base.html" %} {% load i18n %} {% load crispy_forms_tags %}

<!--Block Header-->
{% block head_title %} {% translate "Password Reset" %} {% endblock head_title %}

<!--Block Content-->
{% block content %}
<div class="container">
  <div class="row h-100 justify-content-center align-items-center">
    <div class="col-md-4 mt-5">
      <div class="card shadow-md mt-5">
        <div class="card-header text-center" style="background-color: #02474c">
          <legend style="color: #ffffff">Forgot your password?</legend>
          <h6 style="color: #ffffff">Enter your email address to reset password</h6>
        </div>

        <div class="card-body">
          <form
            method="POST"
            action="{% url 'accounts:login' %}"
            enctype="multipart/form-data"
          >
            {%csrf_token%} {{form|crispy}}

            <!-- Submit button -->
            <button
              type="submit"
              class="btn btn-outline-primary col-md-12 btn-block mb-4 mt-3"
            >
              Reset password
            </button>

            <!-- Register buttons -->
            <div class="text-center">
              <p>
                <a href="{%url 'accounts:login'%}">Back to login</a>
              </p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

modules/templates/accounts/password_reset_complete.html
{% extends "accounts/base.html" %} {% load i18n %}

<!--Block Header-->
{% block head_title %} {% translate "Password Reset Success" %} {% endblock head_title %}

modules/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %} {% load i18n %} {% load crispy_forms_tags %}

<!--Block Header-->
{% block head_title %} {% translate "Password Confirm" %} {% endblock head_title %}

modules/templates/accounts/password_reset_done.html
{% extends "accounts/base.html" %} {% load i18n %} {% load crispy_forms_tags %}

<!--Block Header-->
{% block head_title %} {% translate "Password Reset Done" %} {% endblock head_title %}

modules/templates/accounts/signup.html
{% extends "accounts/base.html" %} {% load i18n %} {% load crispy_forms_tags %}

<!--Block Header-->
{% block head_title %} {% translate "Sign Up" %} {% endblock head_title %}

<!--Block Content-->
{% block content %}
<div class="container">
  <div class="row h-100 justify-content-center align-items-center">
    <div class="col-md-5 mt-2">
      <div class="card shadow-md mt-5">
        <div class="card-header text-center" style="background-color: #02474c">
          <legend style="color: #ffffff">Let's get started,</legend>
          <h6 style="color: #ffffff">Create a new account to continue</h6>
        </div>

        <div class="card-body">
          <form
            method="POST"
            action="{% url 'accounts:signup' %}"
            enctype="multipart/form-data"
          >
            {%csrf_token%} {{form|crispy}}
          

            <!-- Submit button -->
            <button
              type="submit"
              class="btn btn-outline-primary col-md-12 btn-block mb-4 mt-3"
            >
              Sign up
            </button>

            <!-- Register buttons -->
            <div class="text-center">
              <p>
                Already have an account?
                <a href="{%url 'accounts:login'%}">Login Here</a>
              </p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}